export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_CARS_PENDING = "REQUEST_CARS_PENDING";
export const REQUEST_CARS_SUCESS = "REQUEST_CARS_SUCESS";
export const REQUEST_CARS_FAILED = "REQUEST_CARS_FAILED";
