import React, { Component } from "react";
import Enzyme, { shallow } from "enzyme";
import EnzymeAdapter from "enzyme-adapter-react-16";
import ErrorBoundary from "./components/ErrorBoundary";

Enzyme.configure({ adapter: new EnzymeAdapter() });

class ComponentWithError extends Component {
  render() {
    return (
      <div>
        <input type="text" value={null} />
      </div>
    );
  }
}

test("displays error message on error generated by child", () => {
  const wrapper = shallow(
    <ErrorBoundary>
      <ComponentWithError />
    </ErrorBoundary>
  );
  wrapper.setState({ hasError: true });
  console.log(wrapper.debug());
});
