import React, { Component } from "react";
import Enzyme, { shallow } from "enzyme";
import Adapter from "enzyme-adapter-react-16";

import { findByTestAttr, checkProps } from "../test/testUtils";
import ErrorBoundary from "./components/ErrorBoundary";

Enzyme.configure({ adapter: new Adapter() });

class ComponentWithError extends Component {
  render() {
    return (
      <div>
        <input type="text" value={null} />
      </div>
    );
  }
}

test("displays error message on error generated by child", () => {
  const wrapper = shallow(
    <ErrorBoundary>
      <ComponentWithError />
    </ErrorBoundary>
  );
  wrapper.setState({ hasError: true });
  const message = findByTestAttr(wrapper, "error-message");
  expect(message.text().length).not.toBe(0);
});
